class BookInfo {
  const BookInfo({
    required this.hebrew,
    required this.transliteration,
    required this.short,
    required this.chapters,
  });
  final String hebrew;
  final String transliteration;
  final String short; // 3-char abbreviation for compact display
  final int chapters;
}

const List<BookInfo> kBooks = [
  // Torah
  BookInfo(
    hebrew: 'בְּרֵאשִׁית',
    transliteration: 'Bereshit',
    short: 'Ber',
    chapters: 50,
  ),
  BookInfo(
    hebrew: 'שְׁמוֹת',
    transliteration: 'Shemot',
    short: 'She',
    chapters: 40,
  ),
  BookInfo(
    hebrew: 'וַיִּקְרָא',
    transliteration: 'Vayikra',
    short: 'Vay',
    chapters: 27,
  ),
  BookInfo(
    hebrew: 'בְּמִדְבַּר',
    transliteration: 'Bemidbar',
    short: 'Bmd',
    chapters: 36,
  ),
  BookInfo(
    hebrew: 'דְּבָרִים',
    transliteration: 'Devarim',
    short: 'Dev',
    chapters: 34,
  ),
  // Nevi'im — Former Prophets
  BookInfo(
    hebrew: 'יְהוֹשֻׁעַ',
    transliteration: 'Yehoshua',
    short: 'Yho',
    chapters: 24,
  ),
  BookInfo(
    hebrew: 'שׁוֹפְטִים',
    transliteration: 'Shoftim',
    short: 'Sho',
    chapters: 21,
  ),
  BookInfo(
    hebrew: 'שְׁמוּאֵל א׳',
    transliteration: 'Shmuel I',
    short: 'Sh1',
    chapters: 31,
  ),
  BookInfo(
    hebrew: 'שְׁמוּאֵל ב׳',
    transliteration: 'Shmuel II',
    short: 'Sh2',
    chapters: 24,
  ),
  BookInfo(
    hebrew: 'מְלָכִים א׳',
    transliteration: 'Melakhim I',
    short: 'Ml1',
    chapters: 22,
  ),
  BookInfo(
    hebrew: 'מְלָכִים ב׳',
    transliteration: 'Melakhim II',
    short: 'Ml2',
    chapters: 25,
  ),
  // Nevi'im — Latter Prophets (Major)
  BookInfo(
    hebrew: 'יְשַׁעְיָהוּ',
    transliteration: 'Yeshayahu',
    short: 'Ysh',
    chapters: 66,
  ),
  BookInfo(
    hebrew: 'יִרְמְיָהוּ',
    transliteration: 'Yirmeyahu',
    short: 'Yrm',
    chapters: 52,
  ),
  BookInfo(
    hebrew: 'יְחֶזְקֵאל',
    transliteration: 'Yehezkel',
    short: 'Yhz',
    chapters: 48,
  ),
  // Nevi'im — Latter Prophets (Minor / Trei Asar)
  BookInfo(
    hebrew: 'הוֹשֵׁעַ',
    transliteration: 'Hoshea',
    short: 'Hos',
    chapters: 14,
  ),
  BookInfo(
    hebrew: 'יוֹאֵל',
    transliteration: 'Yoel',
    short: 'Yol',
    chapters: 4,
  ),
  BookInfo(
    hebrew: 'עָמוֹס',
    transliteration: 'Amos',
    short: 'Amo',
    chapters: 9,
  ),
  BookInfo(
    hebrew: 'עֹבַדְיָה',
    transliteration: 'Ovadyah',
    short: 'Ova',
    chapters: 1,
  ),
  BookInfo(
    hebrew: 'יוֹנָה',
    transliteration: 'Yona',
    short: 'Yon',
    chapters: 4,
  ),
  BookInfo(
    hebrew: 'מִיכָה',
    transliteration: 'Mikha',
    short: 'Mik',
    chapters: 7,
  ),
  BookInfo(
    hebrew: 'נַחוּם',
    transliteration: 'Nahum',
    short: 'Nah',
    chapters: 3,
  ),
  BookInfo(
    hebrew: 'חֲבַקּוּק',
    transliteration: 'Habakkuk',
    short: 'Hab',
    chapters: 3,
  ),
  BookInfo(
    hebrew: 'צְפַנְיָה',
    transliteration: 'Tsefanya',
    short: 'Tsf',
    chapters: 3,
  ),
  BookInfo(
    hebrew: 'חַגַּי',
    transliteration: 'Haggai',
    short: 'Hag',
    chapters: 2,
  ),
  BookInfo(
    hebrew: 'זְכַרְיָה',
    transliteration: 'Zekharyah',
    short: 'Zek',
    chapters: 14,
  ),
  BookInfo(
    hebrew: 'מַלְאָכִי',
    transliteration: 'Malakhi',
    short: 'Mal',
    chapters: 3,
  ),
  // Ketuvim
  BookInfo(
    hebrew: 'תְּהִלִּים',
    transliteration: 'Tehillim',
    short: 'Teh',
    chapters: 150,
  ),
  BookInfo(
    hebrew: 'מִשְׁלֵי',
    transliteration: 'Mishlei',
    short: 'Msh',
    chapters: 31,
  ),
  BookInfo(
    hebrew: 'אִיּוֹב',
    transliteration: 'Iyyov',
    short: 'Iyy',
    chapters: 42,
  ),
  BookInfo(
    hebrew: 'שִׁיר הַשִּׁירִים',
    transliteration: 'Shir HaShirim',
    short: 'ShH',
    chapters: 8,
  ),
  BookInfo(hebrew: 'רוּת', transliteration: 'Ruth', short: 'Rut', chapters: 4),
  BookInfo(
    hebrew: 'אֵיכָה',
    transliteration: 'Eikha',
    short: 'Eik',
    chapters: 5,
  ),
  BookInfo(
    hebrew: 'קֹהֶלֶת',
    transliteration: 'Kohelet',
    short: 'Koh',
    chapters: 12,
  ),
  BookInfo(
    hebrew: 'אֶסְתֵּר',
    transliteration: 'Esther',
    short: 'Est',
    chapters: 10,
  ),
  BookInfo(
    hebrew: 'דָּנִיֵּאל',
    transliteration: 'Daniel',
    short: 'Dan',
    chapters: 12,
  ),
  BookInfo(
    hebrew: 'עֶזְרָא',
    transliteration: 'Ezra',
    short: 'Ezr',
    chapters: 10,
  ),
  BookInfo(
    hebrew: 'נְחֶמְיָה',
    transliteration: 'Nechemiah',
    short: 'Nch',
    chapters: 13,
  ),
  BookInfo(
    hebrew: 'דִּבְרֵי הַיָּמִים א׳',
    transliteration: 'Divrei HaYamim I',
    short: 'DH1',
    chapters: 29,
  ),
  BookInfo(
    hebrew: 'דִּבְרֵי הַיָּמִים ב׳',
    transliteration: 'Divrei HaYamim II',
    short: 'DH2',
    chapters: 36,
  ),
  // Brit Khadasha (NT) — Hebrew transliteration from the Peshitta
  BookInfo(
    hebrew: 'מַתַּי',
    transliteration: 'Mattai',
    short: 'Mat',
    chapters: 28,
  ),
  BookInfo(
    hebrew: 'מַרְקוֹס',
    transliteration: 'Marqos',
    short: 'Mrq',
    chapters: 16,
  ),
  BookInfo(
    hebrew: 'לוּקָא',
    transliteration: 'Luqa',
    short: 'Luq',
    chapters: 24,
  ),
  BookInfo(
    hebrew: 'יוֹחָנָן',
    transliteration: 'Yoḥanan',
    short: 'Yoh',
    chapters: 21,
  ),
  BookInfo(
    hebrew: 'מַעֲשֵׂי הַשְּׁלִיחִים',
    transliteration: "Ma'asei HaShlihim",
    short: 'Maa',
    chapters: 28,
  ),
  BookInfo(
    hebrew: 'רוֹמִיִּים',
    transliteration: 'Romiyim',
    short: 'Rom',
    chapters: 16,
  ),
  BookInfo(
    hebrew: 'קוֹרִינְתִּיִּים א׳',
    transliteration: 'Qorintiyim I',
    short: 'Qr1',
    chapters: 16,
  ),
  BookInfo(
    hebrew: 'קוֹרִינְתִּיִּים ב׳',
    transliteration: 'Qorintiyim II',
    short: 'Qr2',
    chapters: 13,
  ),
  BookInfo(
    hebrew: 'גַּלָּטִיִּים',
    transliteration: 'Galatiyim',
    short: 'Gal',
    chapters: 6,
  ),
  BookInfo(
    hebrew: 'אֶפֶסִיִּים',
    transliteration: 'Efesiyim',
    short: 'Efe',
    chapters: 6,
  ),
  BookInfo(
    hebrew: 'פִּילִפִּיִּים',
    transliteration: 'Filipiyim',
    short: 'Flp',
    chapters: 4,
  ),
  BookInfo(
    hebrew: 'קוֹלוֹסִּיִּים',
    transliteration: 'Kolosiyim',
    short: 'Kol',
    chapters: 4,
  ),
  BookInfo(
    hebrew: 'תֶּסָּלוֹנִיקִיִּים א׳',
    transliteration: 'Tessaluniqiyim I',
    short: 'Ts1',
    chapters: 5,
  ),
  BookInfo(
    hebrew: 'תֶּסָּלוֹנִיקִיִּים ב׳',
    transliteration: 'Tessaluniqiyim II',
    short: 'Ts2',
    chapters: 3,
  ),
  BookInfo(
    hebrew: 'טִימוֹתֵאוֹס א׳',
    transliteration: 'Timotheos I',
    short: 'Tm1',
    chapters: 6,
  ),
  BookInfo(
    hebrew: 'טִימוֹתֵאוֹס ב׳',
    transliteration: 'Timotheos II',
    short: 'Tm2',
    chapters: 4,
  ),
  BookInfo(
    hebrew: 'טִיטוֹס',
    transliteration: 'Titos',
    short: 'Tit',
    chapters: 3,
  ),
  BookInfo(
    hebrew: 'פִּילֵמוֹן',
    transliteration: 'Filemon',
    short: 'Flm',
    chapters: 1,
  ),
  BookInfo(
    hebrew: 'עִבְרִיִּים',
    transliteration: 'Ivriyim',
    short: 'Ivr',
    chapters: 13,
  ),
  BookInfo(
    hebrew: 'יַעֲקוֹב',
    transliteration: 'Yaakov',
    short: 'Yak',
    chapters: 5,
  ),
  BookInfo(
    hebrew: 'פֶּטְרוֹס א׳',
    transliteration: 'Petros I',
    short: 'Pt1',
    chapters: 5,
  ),
  BookInfo(
    hebrew: 'פֶּטְרוֹס ב׳',
    transliteration: 'Petros II',
    short: 'Pt2',
    chapters: 3,
  ),
  BookInfo(
    hebrew: 'יוֹחָנָן א׳',
    transliteration: 'Yoḥanan I',
    short: 'Yo1',
    chapters: 5,
  ),
  BookInfo(
    hebrew: 'יוֹחָנָן ב׳',
    transliteration: 'Yoḥanan II',
    short: 'Yo2',
    chapters: 1,
  ),
  BookInfo(
    hebrew: 'יוֹחָנָן ג׳',
    transliteration: 'Yoḥanan III',
    short: 'Yo3',
    chapters: 1,
  ),
  BookInfo(
    hebrew: 'יְהוּדָה',
    transliteration: 'Yehuda',
    short: 'Yhd',
    chapters: 1,
  ),
  BookInfo(
    hebrew: 'גִּלָּיוֹן',
    transliteration: 'Gilyon',
    short: 'Gil',
    chapters: 22,
  ),
];

/// Standard English names, ordered to match [kBooks].
const List<String> kEnglishBookNames = [
  'Genesis',
  'Exodus',
  'Leviticus',
  'Numbers',
  'Deuteronomy',
  'Joshua',
  'Judges',
  '1 Samuel',
  '2 Samuel',
  '1 Kings',
  '2 Kings',
  'Isaiah',
  'Jeremiah',
  'Ezekiel',
  'Hosea',
  'Joel',
  'Amos',
  'Obadiah',
  'Jonah',
  'Micah',
  'Nahum',
  'Habakkuk',
  'Zephaniah',
  'Haggai',
  'Zechariah',
  'Malachi',
  'Psalms',
  'Proverbs',
  'Job',
  'Song of Songs',
  'Ruth',
  'Lamentations',
  'Ecclesiastes',
  'Esther',
  'Daniel',
  'Ezra',
  'Nehemiah',
  '1 Chronicles',
  '2 Chronicles',
  'Matthew',
  'Mark',
  'Luke',
  'John',
  'Acts',
  'Romans',
  '1 Corinthians',
  '2 Corinthians',
  'Galatians',
  'Ephesians',
  'Philippians',
  'Colossians',
  '1 Thessalonians',
  '2 Thessalonians',
  '1 Timothy',
  '2 Timothy',
  'Titus',
  'Philemon',
  'Hebrews',
  'James',
  '1 Peter',
  '2 Peter',
  '1 John',
  '2 John',
  '3 John',
  'Jude',
  'Revelation',
];

/// Compact English labels for book-picker chips, ordered to match [kBooks].
const List<String> kEnglishBookAbbreviations = [
  'Gen',
  'Exod',
  'Lev',
  'Num',
  'Deut',
  'Josh',
  'Judg',
  '1 Sam',
  '2 Sam',
  '1 Kgs',
  '2 Kgs',
  'Isa',
  'Jer',
  'Ezek',
  'Hos',
  'Joel',
  'Amos',
  'Obad',
  'Jonah',
  'Mic',
  'Nah',
  'Hab',
  'Zeph',
  'Hag',
  'Zech',
  'Mal',
  'Ps',
  'Prov',
  'Job',
  'Song',
  'Ruth',
  'Lam',
  'Eccl',
  'Esth',
  'Dan',
  'Ezra',
  'Neh',
  '1 Chr',
  '2 Chr',
  'Matt',
  'Mark',
  'Luke',
  'John',
  'Acts',
  'Rom',
  '1 Cor',
  '2 Cor',
  'Gal',
  'Eph',
  'Phil',
  'Col',
  '1 Thess',
  '2 Thess',
  '1 Tim',
  '2 Tim',
  'Titus',
  'Phlm',
  'Heb',
  'Jas',
  '1 Pet',
  '2 Pet',
  '1 John',
  '2 John',
  '3 John',
  'Jude',
  'Rev',
];

String bookDisplayName(int bookIndex, {required bool useEnglish}) => useEnglish
    ? kEnglishBookNames[bookIndex]
    : kBooks[bookIndex].transliteration;

String bookSelectorLabel(int bookIndex, {required bool useEnglish}) =>
    useEnglish ? kEnglishBookAbbreviations[bookIndex] : kBooks[bookIndex].short;
