import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

/// Identifier of the bundled database build, as an ISO-8601 UTC timestamp
/// (`2026-07-25T20:31:12Z`).
///
/// The value is generated by `tool/sync-dbs.sh` from the databases themselves
/// — their build time, not a number anyone maintains — and written beside them
/// as `assets/db/version.txt`. It ships as a sidecar rather than being read out
/// of the database so the installer can compare versions without opening
/// SQLite, and so both the native and web runtimes can show it.
///
/// Comparison is plain string equality: any difference means the bundled
/// databases are not the installed ones. The format also orders
/// lexicographically, which is what lets a sync server decide whether it holds
/// a newer build than a client.
const _versionAsset = 'assets/db/version.txt';

const unknownDbVersion = 'unknown';

Future<String> bundledDbVersion() async {
  try {
    return (await rootBundle.loadString(_versionAsset)).trim();
  } on FlutterError {
    // No sidecar: databases synced by an older tool, or a build that skipped
    // tool/sync-dbs.sh. Reinstalling on every launch would be worse than
    // showing the gap, so callers treat this as a stable unknown version.
    return unknownDbVersion;
  }
}
